### ISSUE TITLE
Missing files in solution

### ISSUE THREAD

**Issue by vovanb** [rd003/MovieStoreMvc#2]
Hi 
There is no SQL files in project to build DB,. The folder Data did not included

**Comment by rd003** [comment]
It follows code first approach so you should not directly execute the sql
script.


You have to generate db through migrations.

Delete old migration files.
Then run commands
Add-migration anyName
Uodate-database

**Comment by TusCute** [comment]
Can you guide people how to use it please
Thanks bro

**Comment by TusCute** [comment]
![image](https://github.com/rd003/MovieStoreMvc/assets/143469019/9767ca11-b436-4cb3-97c3-1f5c712f60d3)
how to login

**Comment by rd003** [comment]
Please check the `readme.md` file. I have updated it.
